# Жёстко фиксируем монитор (Wayland-имя порта)
monitor=HDMI-A-1,1920x1080@144,0x0,1

# Переменные окружения для NVIDIA
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Аппаратный курсор (чтобы не лагал)
cursor {
    no_hardware_cursors = false
}

# Отключаем анимации и логотип для быстрого старта
animations {
    enabled = false
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 0
}
